### PR TITLE
Core File Based Configuration

### PR DESCRIPTION
**Pull request by opalmer**
This splits the core file based configuration changes off from #420 into its own review.  This should be something we can merge before the main changes land.

This will add support for file based configuration without changing any other code quite yet (which would happen in #420).

### CODE REVIEW

**Comment by opalmer** [comment]
@guidow, please take a look at this review first.  This will add support for file based configuration without changing any other code quite yet (which would happen in #420).

**Comment by opalmer** [comment]
@guidow, I can close this PR if you'd prefer to review these changes with #420 too.

**Comment by guidow** [comment]
This looks good and seems to work well so far.

**Comment by opalmer** [comment]
Thanks.  I'll go ahead and merge this tomorrow then unless you have anything else or see issues with it between now and then.

**Pull request merged**
