### PR TITLE
Remove Debug Configuration

### PR DESCRIPTION
**Pull request by opalmer**

### CODE REVIEW

**Comment by opalmer** [comment]
@guidow PTAL, I've pulled this out of #420 since this is something we can discuss/merge outside of that larger change.

**Comment by guidow** [comment]
I'm actually using the debug configuration on my development machine. As far as I can tell, the second commit there should make sure it still works for this, but I'm going to have to actually test that when I get back to the office – which won't be before wednesday.

**Comment by opalmer** [comment]
Thanks, take your time.  No real rush here since #420 is still a work in progress for another day or so and this PR is just a related subset to chose changes.

**Comment by guidow** [comment]
I've had a chance to test this now. It still works, and I have no objections left to merging this.

**Pull request merged**
