### PR TITLE
Collect runtime statistics about number of agents

### PR DESCRIPTION
**Pull request by guidow**
Users can / should specify a different database for the statistics, including on a different host. This is advisable because the statistics tables could become very large, and operations on the statistics database could become expensive in terms of CPU cycles, RAM, and I/O bandwidth, both for the python app and for the database server. There are no references between the normal tables and the statistics tables, and the statistics tables will not be needed for normal operations of pyfarm.

### CODE REVIEW

**Comment by opalmer** [comment]
I have not done a deep dive on the code yet, this is in progress after all, but overall the design seems like it would work well.  One question I have though is if you've considered using something like statsd/graphite to handle the stats and graphs?  The approach being taken here is better for a number of reasons I think (nicer display, more control over how we/where the data is displayed, does not require extra services, etc), I just though I might throw the suggestion out there in case you where thinking you'd rather have something more dedicated for logging and rendering statistics.

**Comment by guidow** [comment]
> One question I have though is if you've considered using something like statsd/graphite to handle the stats and graphs?

No, I've never heard of either of those.

**Comment by opalmer** [comment]
They might be worth taking a look at.  Statsd and graphite work well together and, at least in my own experience, are a good solution if you don't know what all the stats you'll ever want are in advance.  

With statsd you don't have to predefine the stats you want to log or how they're going to be stored since the application handles both of these cases for you.  With graphite, you also don't have to implement functions to draw the graphs yourself and many of the commonly used graphing functions are all already provided for you.  

It does add a bit to the setup but it would probably be more flexible in the end.  There's [some docs here on a complete setup](https://www.digitalocean.com/community/tutorials/an-introduction-to-tracking-statistics-with-graphite-statsd-and-collectd) if you're at all interested.  It's part of a series and goes into quite a bit more depth than I have here.

In the long run, I think statsd/graphite or something like it would probably help quite a bit when it comes to understanding a farm's overall performance especially around the scheduler.  But I don't know if this is where we should start adding or if you think it's not worth the extra setup steps.  It still wouldn't be a requirement, much like you're starting with here, so smaller farms could do without (API calls won't fail if the server is down).

**Comment by guidow** [comment]
I've had a look at graphite and statsd, and they really do look interesting.

However, the added complexity that system brings with it seems a bit too much for now. Maybe we can add support for that later – shouldn't be too hard on the pyfarm-side of things – but for now, I'd prefer to merge this statistics branch instead.

**Comment by opalmer** [comment]
Alright, well thanks for taking to time to have a look.  Hopefully we can eventually integrate graphite/statsd eventually but for now I don't have a problem with merging this.

**Pull request merged**
